name: real_life_city_commute
description: Real-life style city commute and place graph example.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  taerae:
    path: ../../packages/taerae_core
