name: real_life_personal_notes_rag
description: Real-life personal notes retrieval with GraphRAG.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  taerae:
    path: ../../packages/taerae_core
